/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gervai;

import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import javax.swing.JOptionPane;
import org.json.JSONArray;
import org.json.JSONObject;

/**
 *
 * @author Sam
 */
public class ViewUser extends javax.swing.JFrame {
    static String username = "Fail";
    private final String WEBSITE_ADDRESS = "http://gervai.com";
    private final String GET_URL = WEBSITE_ADDRESS + "/api/get";
    private final String USER_AGENT = "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)";
    int[] data;
    /**
     * Creates new form LoginForm
     */
    public ViewUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlePanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        lblEmail = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();
        btnViewGraph = new javax.swing.JButton();
        btnGetUser = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("View Profile");

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblEmail.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmail.setText("Username");

        tfUsername.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        btnViewGraph.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnViewGraph.setText("View Graph");
        btnViewGraph.setFocusPainted(false);
        btnViewGraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewGraphActionPerformed(evt);
            }
        });

        btnGetUser.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnGetUser.setText("View User Details");
        btnGetUser.setFocusPainted(false);
        btnGetUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(btnViewGraph)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnGetUser))
                            .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 64, Short.MAX_VALUE)))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewGraph)
                    .addComponent(btnGetUser))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(405, 217));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewGraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewGraphActionPerformed
        username = tfUsername.getText();
        if (username.isEmpty()) {
            throwError("Please Enter a user name!");
            return;
        }
        //System.out.println(username);
        try {
            JSONObject objView = new JSONObject();
            String postRequest = sendPost("username=" + username, GET_URL);
            if (postRequest.isEmpty()) {
                return;
            }
            objView = new JSONObject(postRequest);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        SurveyPanel.dataToDraw = getData();
        SurveyGraph.main();
    }//GEN-LAST:event_btnViewGraphActionPerformed

    private void btnGetUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetUserActionPerformed
        // TODO add your handling code here:
        username = tfUsername.getText();
        if (username.isEmpty()) {
            throwError("Please Enter a user name!");
            return;
        }
        try {
            JSONObject objView = new JSONObject();
            String postRequest = sendPost("username=" + username, GET_URL);
            if (postRequest.isEmpty()) {
                return;
            }
            objView = new JSONObject(postRequest);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        getUser();
    }//GEN-LAST:event_btnGetUserActionPerformed

    private void throwError(String errormsg) {
        JOptionPane.showMessageDialog(this, errormsg, "Error", JOptionPane.ERROR_MESSAGE);
    }

    private void throwError(String errormsg, String title) {
        JOptionPane.showMessageDialog(this, errormsg, title, JOptionPane.ERROR_MESSAGE);
    }
    
    
    public String sendPost(String params, String url) throws Exception {
        URL obj = new URL(url);
        HttpURLConnection con = (HttpURLConnection) obj.openConnection();
        //Sets the properties
        con.setRequestMethod("POST");
        con.addRequestProperty("User-Agent", USER_AGENT);
        con.setRequestProperty("Accept-Language", "en-US,en;q=0.5");
        //Writes the bytes, sends it off
        con.setDoOutput(true);
        try {
            try (DataOutputStream wr = new DataOutputStream(con.getOutputStream())) {
                wr.writeBytes(params);
                wr.flush();
            }
        } catch (IOException ex) {
            throwError(ex.toString());
            return "";
        }
        //Gets the response
        int responseCode = con.getResponseCode();
        System.out.println("Sending 'POST' request to URL: " + url);
        System.out.println("Post parameters: " + params);
        System.out.println("Response Code: " + responseCode);
        System.out.println();
        if (responseCode >= 400) {
            throwError("No data from the user available", "HTTP - " + responseCode);
            return "";
        }
        StringBuffer response;
        try (BufferedReader in = new BufferedReader(
                new InputStreamReader(con.getInputStream()))) {
            String inputLine;
            response = new StringBuffer();
            while ((inputLine = in.readLine()) != null) {
                response.append(inputLine);
            }
        }
        //System.out.println("Response: " + response.toString());
        return response.toString();
    }
    
    public int[] getData() {
        try {
            JSONObject jsonResponse = new JSONObject(sendPost("username=" + ViewUser.username, GET_URL));
            System.out.println(sendPost("username=" + ViewUser.username, GET_URL));
            JSONArray postArray = jsonResponse.getJSONArray("entries");
            data = new int[postArray.length()];
            for (int i = 0; i < postArray.length(); i++) {
                data[i] = postArray.getJSONObject(i).getBoolean("correct") ? 1 : 0;
            }
        } catch (Exception e) {
            e.printStackTrace();
            data[0] = -1;
        }
        return data;
    }
    
    public void getUser() {
        try {
            JSONObject jsonResponse = new JSONObject(sendPost("username=" + ViewUser.username, GET_URL));
            System.out.println(sendPost("username=" + ViewUser.username, GET_URL));
            JSONArray postArray = jsonResponse.getJSONArray("profile");
            JSONObject object = postArray.getJSONObject(0);
            JSONObject jj = object.getJSONObject("profile");
            String age=Integer.toString(jj.getInt("age"));
            String father=jj.getString("fathersName");
            String first=jj.getString("firstName");
            String full=jj.getString("fullName");
            String gender=jj.getString("gender");
            String last=jj.getString("lastName");
            String mother=jj.getString("mothersName");
            //System.out.println(jj.getString("fathersName"));
            MainWindow.tfAge.setText(age);
            MainWindow.tfFather.setText(father);
            MainWindow.tfFirst.setText(first);
            MainWindow.tfFull.setText(full);
            MainWindow.tfGender.setText(gender);
            MainWindow.tfLast.setText(last);
            MainWindow.tfMother.setText(mother);
        } catch (Exception e) {
            e.printStackTrace();
        }
        MainWindow.main();
    }
    /*
     private void openWebPage(URI uri) {
     Desktop desktop = Desktop.isDesktopSupported() ? Desktop.getDesktop() : null;
     if (desktop != null && desktop.isSupported(Desktop.Action.BROWSE)) {
     try {
     desktop.browse(uri);
     } catch (Exception e) {
     e.printStackTrace();
     }
     } else {
     System.out.println("This operation is not supported!");
     }
     }
     */

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGetUser;
    private javax.swing.JButton btnViewGraph;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField tfUsername;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables
}
